dist: xenial
language: java
sudo: required
jdk:
- openjdk8
script:
- "cd functional-examples && ./gradlew assemble"
- "cd chain-of-command && ./gradlew assemble"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"