name: All Examples Build Verification

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODEBUG: x509sha1=1

jobs:
  examples-build-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.9'
      - name: Install Nats Server
        uses: scottf/install-nats-io-server-ubuntu@v1
      - name: Check out code
        uses: actions/checkout@v3
      - name: Chain of Command
        run: |
          pushd chain-of-command
          chmod +x gradlew
          ./gradlew compileJava
          popd
      - name: Core Reply Request Patterns
        run: |
          pushd core-reply-request-patterns
          chmod +x gradlew
          ./gradlew compileJava
          popd
      - name: Encoding
        run: |
          pushd encoding
          chmod +x gradlew
          ./gradlew compileJava
          popd
      - name: File Transfer Manual
        run: |
          pushd file-transfer-manual
          chmod +x gradlew
          ./gradlew compileJava
          popd
      - name: File Transfer Object Store
        run: |
          pushd file-transfer-object-store
          chmod +x gradlew
          ./gradlew compileJava
          popd
      - name: Functional Examples
        run: |
          pushd functional-examples
          chmod +x gradlew
          ./gradlew compileJava
          popd
      - name: Hello World
        run: |
          pushd hello-world
          chmod +x gradlew
          ./gradlew test
          popd
      - name: Js Multi Tool
        run: |
          pushd js-multi-tool
          chmod +x gradlew
          ./gradlew clean compileJava
          mvn clean compile
          popd
      - name: Js Over Core
        run: |
          pushd js-over-core
          chmod +x gradlew
          ./gradlew clean compileJava
          popd
      - name: Multi Subject Worker
        run: |
          pushd multi-subject-worker
          chmod +x gradlew
          ./gradlew clean compileJava
          popd
      - name: OCSP
        run: |
          pushd ocsp
          chmod +x gradlew
          ./gradlew compileJava
          popd
#      - name: Server Pool
#        run: |
#          pushd server-pool
#          chmod +x gradlew
#          ./gradlew compileJava
#          popd
      - name: Starter Gradle Groovy
        run: |
          pushd starter-gradle-groovy
          chmod +x gradlew
          ./gradlew test
          popd
      - name: Starter Gradle Kotlin
        run: |
          pushd starter-gradle-kotlin
          chmod +x gradlew
          ./gradlew test
          popd
      - name: Starter Maven
        run: |
          pushd starter-maven
          mvn test
          popd
